version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/zer-far/writefreely"