version: "3"
services:
  web:
    image: "writeas/writefreely"
    volumes:
      - "web-data:/go/keys"
      - "./config.ini.docker-compose:/go/config.ini"
    ports:
      - "8080:8080"
    networks:
      - writefreely
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: "mariadb:latest"
    volumes:
      - db-data:/var/lib/mysql/writefreely
    networks:
      - writefreely
    environment:
      - MYSQL_DATABASE=writefreely
      - MYSQL_ROOT_PASSWORD=changeme
    restart: unless-stopped

volumes:
  web-data:
  db-data:

networks:
  writefreely:
